name: new_flutter_tapjoy
description: Tapjoy plugin for both Android & iOS
version: 0.0.4
homepage: https://github.com/Maciejj1/Flutter_Tapjoy_Plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.itlight.new_flutter_tapjoy
        pluginClass: NewFlutterTapjoyPlugin
      ios:
        pluginClass: NewFlutterTapjoyPlugin

  